version: "3"
services:
  db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5434"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    user: 503:20
    healthcheck:
      test: "pg_isready --username=postgres"
      interval: 10s
      timeout: 5s
      retries: 5
